version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 8
    labels:
      - chore
      - devops
    groups:
      web-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: "/apps/server"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - chore
      - devops

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - chore
      - devops
